config/routes.rb
Stanceshare::Application.routes.draw do
  resources :parts

  devise_for :users
  root "parts#index"
  get "about" => "pages#about" # creates about path

  

end

app/models/part.rb
class Part < ActiveRecord::Base
	belongs_to :user
	has_attached_file :image, :styles => { :medium => "300x300", :thumb => "100x100 "}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :parts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  before_action :set_part, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @parts = Part.all.order("created_at DESC")
  end

  def show
  end

  def new
    @part = current_user.parts.build
  end

  def edit
  end

  def create
    @part = current_user.parts.build(part_params)
    if @part.save
      redirect_to @part, notice: 'Part was successfully created.' 
    else
     render action: 'new' 
    end
  end

  def update
    if @part.update(part_params)
      redirect_to @part, notice: 'Part was successfully updated.' 
    else
      render action: 'edit' 
    end
  end

  def destroy
    @part.destroy
    redirect_to parts_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_part
      @part = Part.find(params[:id])
    end

    def correct_user
      @part = current_user.parts.find_by(id: params[:id])
      redirect_to parts_path, notice: "Yooo, you not allowed to do that son!" if @part.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def part_params
      params.require(:part).permit(:description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container"  >
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "StanceShare", root_path, class: "navbar-brand" %>
    </div> 

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <% if user_signed_in? %>
        <li>
          <%= link_to new_part_path do %>
            <span class="glyphicon glyphicon-road">New Part</span>
          <% end %>
        </li>
        <li><%= link_to "Account Settings", edit_user_registration_path %></li>
        <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li> 
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StanceShare</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %> 

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	
	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-info") %>
			
		<% end %>
		<%= yield %>
	</div>

</body>
</html>

app/views/pages/_home.html.erb
<div class="jumbotron center">
	<h1>Welcome to Stanceshare!</h1>
	<p>
		<%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
		<%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
	</p>
</div>

app/views/pages/about.html.erb
<h1>About StanceShare</h1>
<p>page WIP</p>

app/views/pages/home.html.erb
<div class="jumbotron">
	<h1>Welcome to Stanceshare!</h1>
	<% if user_signed_in? %>
		# do something 
	<% else %>
		<p>
			<%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
			<%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
		</p>
	<% end %>
</div>

app/views/parts/_form.html.erb
<%= form_for @part, html: { multipart: true } do |f| %>
  <% if @part.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@part.errors.count, "error") %> prohibited this part from being saved:</h2>

      <ul>
      <% @part.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/parts/edit.html.erb
<h1>Editing part</h1>

<%= render 'form' %>

<%= link_to 'Show', @part %> |
<%= link_to 'Back', parts_path %>

app/views/parts/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>

<div id="parts" class="transitions-enabled">
  <% @parts.each do |part| %>
    <div class="box panel panel-default">
      <%= link_to image_tag(part.image.url(:medium)), part %>
      <div class="panel-body">
        <%= part.description %>
        <%= part.user.email if part.user %>
        <strong><%= part.user.email if part.user %></strong>
        <% if part.user == current_user %>
          <div class="actions">
            <%= link_to edit_part_path(part) do %>
              <span class="glyphicon glyphicon-edit"></span>
              Edit
            <% end %>
            <%= link_to part, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <span class="glyphicon glyphicon-trash"></span>
              Delete
            <% end %>
          </div>
        <% end %>
      </div>
     </div> 
  <% end %>
</div>

app/views/parts/new.html.erb
<h1>New part</h1>

<%= render 'form' %>

<%= link_to 'Back', parts_path %>

app/views/parts/show.html.erb
<%= link_to 'Back', parts_path %>

<div class="row">
	<div class="col-md-offset-2 col-md-8">
		<div class="panel panel-default">
			<div class="panel-heading center">
				<%= image_tag @part.image.url(:medium) %>
			</div>
			<div class="panel-body">
				<p><%= @part.description %></p>
				<p><strong><%= @part.user.email if @part.user %></strong></p>

				<% if @part.user == current_user %>
					<%= link_to edit_part_path(@part) do %>
						<span class="glyphicon glyphicon-edit"></span>
						Edit
					<% end %>

			</div>
		</div>
	</div>
</div>